{
    'name': 'SQL Server Integration',
    'version': '16.0.0.0.0',
    'category': 'Extra Tools',
    'summary': 'SQL Server data integration',
    'sequence': 1,
    'description': """SQL Server data integration""",
    'author': 'ZakheniICT',
    'website':'www.zakhenict.co.za',
    'license':'LGPL-3',
    'depends': ['base'],
    'data': [
        'security/ir.model.access.csv',
        'views/sql_connection_views.xml',
        'views/sql_revenue_views.xml',
        'views/sql_mine_contract_views.xml',
        'views/sql_logbook_views.xml',
        'views/sql_vehicle_inspection_views.xml',
        'views/sql_bins_analysis_views.xml',
        'views/sql_waste_analysis_views.xml',
        'views/sql_bookings_analysis_views.xml',
        'views/sql_disposal_rate_views.xml',
        'views/sql_disposal_rate_report_views.xml',
        'views/sql_rental_rate_views.xml',
        'views/sql_transport_rate_views.xml',
        'views/sql_transport_report_views.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'external_dependencies': {
        'python': ['pymssql'],
    },
} 